% SPDX-FileCopyrightText: 2024 Binsparse Developers
%
% SPDX-License-Identifier: BSD-3-Clause

function matrix = bsp_matrix_create(varargin)
% BSP_MATRIX_CREATE - Create a Binsparse matrix struct
%
% Creates a MATLAB struct analogous to the C bsp_matrix_t structure.
% The struct contains four native MATLAB arrays and metadata fields.
%
% Usage:
%   matrix = bsp_matrix_create()                    % Empty matrix
%   matrix = bsp_matrix_create(values, indices_0, indices_1, pointers_to_1, ...
%                              nrows, ncols, nnz, is_iso, format, structure)
%
% Fields:
%   values       - MATLAB array of matrix values
%   indices_0    - MATLAB array of first dimension indices
%   indices_1    - MATLAB array of second dimension indices
%   pointers_to_1 - MATLAB array of pointers for compressed formats
%   nrows        - Number of rows (integer)
%   ncols        - Number of columns (integer)
%   nnz          - Number of non-zeros (integer)
%   is_iso       - Logical indicating if matrix has single value (logical)
%   format       - Matrix format string ('CSR', 'CSC', 'COO', etc.)
%   structure    - Matrix structure string ('general', 'symmetric', etc.)
%
% Example:
%   % Create empty matrix
%   matrix = bsp_matrix_create();
%
%   % Create COO matrix
%   values = [1.0, 2.0, 3.0];
%   rows = [1, 2, 3];
%   cols = [1, 2, 3];
%   matrix = bsp_matrix_create(values, rows, cols, [], 3, 3, 3, false, 'COO', 'general');

if nargin == 0
    % Create empty/default matrix
    matrix = struct(...
        'values', double([]), ...
        'indices_0', uint64([]), ...
        'indices_1', uint64([]), ...
        'pointers_to_1', uint64([]), ...
        'nrows', uint64(0), ...
        'ncols', uint64(0), ...
        'nnz', uint64(0), ...
        'is_iso', false, ...
        'format', '', ...
        'structure', 'general');

elseif nargin == 10
    % Create matrix with all fields specified
    matrix = struct(...
        'values', varargin{1}, ...
        'indices_0', varargin{2}, ...
        'indices_1', varargin{3}, ...
        'pointers_to_1', varargin{4}, ...
        'nrows', uint64(varargin{5}), ...
        'ncols', uint64(varargin{6}), ...
        'nnz', uint64(varargin{7}), ...
        'is_iso', logical(varargin{8}), ...
        'format', char(varargin{9}), ...
        'structure', char(varargin{10}));

else
    error('bsp_matrix_create:InvalidArgs', ...
          'Expected 0 or 10 arguments, got %d', nargin);
end

end
