# SPDX-FileCopyrightText: 2024 Binsparse Developers
#
# SPDX-License-Identifier: BSD-3-Clause

name: "CI"

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Checks
      uses: pre-commit/action@v3.0.0

  gcc:
    runs-on: 'ubuntu-latest'
    env:
      CXX: g++-12
      CC: gcc-12
    steps:
    - uses: actions/checkout@v4
    - name: CMake
      run: |
        sudo apt-get update
        sudo apt-get install libhdf5-dev $CXX $CC
        cmake -B build
    - name: Build
      run: VERBOSE=true make -C build -j `nproc`
    - name: Test-Matrix
      run: ctest --test-dir ./build/test/bash
    - name: Install-Julia
      run: curl -fsSL https://install.julialang.org | sh
    - name: Install-Finch
      run: julia -e 'using Pkg; Pkg.add("Finch")'
    - name: Test-Tensor
      run: ctest --test-dir ./build/test/julia

  clang:
    runs-on: 'ubuntu-latest'
    env:
      CXX: clang++
      CC: clang
    steps:
    - uses: actions/checkout@v4
    - name: CMake
      run: |
        sudo apt-get update
        sudo apt-get install libhdf5-dev clang
        cmake -B build
    - name: Build
      run: VERBOSE=true make -C build -j `nproc`
    - name: Test-Matrix
      run: ctest --test-dir ./build/test/bash
    - name: Install-Julia
      run: curl -fsSL https://install.julialang.org | sh
    - name: Install-Finch
      run: julia -e 'using Pkg; Pkg.add("Finch")'
    - name: Test-Tensor
      run: ctest --test-dir ./build/test/julia
