# SPDX-FileCopyrightText: 2024 Binsparse Developers
#
# SPDX-License-Identifier: BSD-3-Clause

name: "CI"

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Checks
      uses: pre-commit/action@v3.0.0

  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          - cc:  gcc-12
            cxx: g++-12
          - cc:  clang
            cxx: clang++
    name: ${{ matrix.cc }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v4
    - name: CMake
      run: |
        sudo apt-get update
        sudo apt-get install libhdf5-dev gcc-12 g++-12 clang
        cmake -B build
    - name: Build
      run: VERBOSE=true make -C build -j `nproc`
    - name: Matrix Tests
      run: ctest --test-dir ./build/test/bash
    - name: Install Julia
      run: curl -fsSL https://install.julialang.org | sh -s -- -y
    - name: Disable Julia precompilation
      run: julia -e 'using Pkg; Pkg.add("PrecompileTools"); using PrecompileTools, Preferences; set_preferences!(PrecompileTools, "precompile_workloads" => false; force=true)'
    - name: Install Julia Packages
      run: julia -e 'using Pkg; Pkg.add(["Finch", "HDF5"])'
    - name: Tensor Tests
      run: ctest --test-dir ./build/test/julia
